# Generated by Django 3.2.4 on 2021-06-27 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scripture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verse',
            name='textq',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_meta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scripture.bookmeta'),
        ),
    ]
