# Generated by Django 3.2.4 on 2021-06-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripture', '0002_auto_20210627_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='textq',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
