# Generated by Django 3.2.4 on 2021-08-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripture', '0006_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
