# Generated by Django 3.2.4 on 2021-09-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripture', '0007_blog_last_edited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='identiy',
            new_name='identity',
        ),
        migrations.AlterField(
            model_name='bookmeta',
            name='written_in',
            field=models.CharField(max_length=255),
        ),
    ]
