# Generated by Django 3.2.4 on 2021-09-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripture', '0008_auto_20210925_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmeta',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
