# Generated by Django 3.2.4 on 2021-10-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripture', '0010_user_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
